name: butce_takip
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^1.1.1
  intl: ^0.20.2
  uuid: ^4.5.2
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  # İKON PAKETİNİ BURAYA EKLEDİK:
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  # Resim klasörünü uygulamaya tanıtıyoruz:
  assets:
    - assets/icon/

# --- İKON AYARLARI ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21